
<!-- This script is responsible for generating the response view after deleting an existing task -->

<div class="flex my-auto">
    <div class="w-1/3 mx-auto p-8 bg-neutral-200 rounded-md">
        <div class="text-center">
            <p class="mb-10 text-xl <?php echo $this->txtColor;?>"><?php echo $this->message; ?></p>
            <div class="space-x-12">
                <button class="bg-white text-black px-4 py-2 rounded-md hover:bg-lime-500">
                    <a href="<?php echo WEB_ROOT?>">See all tasks</a>
                </button>
                <button class="bg-white text-black px-4 py-2 rounded-md hover:bg-lime-500">
                <a href="<?php echo WEB_ROOT . "/getinsertform"?>">Create new task</a>
                </button>
                
            </div>
        </div>
    </div>
</div>