<?php 

    $results = $this->results;

    if (isset($results)) : ?>
    
        <div class="w-3/4 mx-auto">

            <div class="w-full text-center mt-2 mb-4">
                <h2 class="text-2xl font-semibold text-center text-orange-400">SEARCH RESULTS LIST</h2>
            </div>
            
        
            <div class="min-w-full">
    
                <?php 
                    foreach ($results as $task){
                        // Not used code
                        //$shortenedText = isset($task['task_details']) ? substr($task['task_details'], 0, 20) : '';
                        include "taskListContent.phtml";
                    } 
                ?>

                <?php else : ?>
                    <p>No tasks to show</p>
                <?php endif; ?>

            </div>

        </div>

