
<!-- This script is responsible for generating the task search form -->

<div class="flex my-auto">
    <div class="w-3/5 mx-auto p-4">
        <h2 class="text-2xl mb-8 font-semibold text-center text-orange-400">SEARCH TASK</h2>
        <form action="getsearchresults" method="post" class="text-orange-400" autocomplete="off">     
            <div class="flex">
                <div class="w-3/4">
                    <!-- Task name -->
                    <label for="task_name_id" class="block text-orange-600">Task name:</label>
                    <input type="text" id="task_name_id" name="task_name" class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500 h-11" placeholder="Optional field">
                </div>
                <div class="w-1/4 mx-4">
                    <!-- Task status -->
                    <label for="task_status_id" class="block text-orange-600">Status:</label>
                    <select id="task_status_id" name="task_status" class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500 h-11">>
                        <option value="All statuses" selected>All statuses</option>
                        <option value="Pending">Pending</option>
                        <option value="In Progress">In Progress</option>
                        <option value="Completed">Completed</option>
                    </select>
                </div>
            </div>

            <div class="flex mt-4 mb-12">
                <div class="flex justify-between w-3/4">
                    <!-- Created By -->
                    <div class="w-60">
                        <label for="task_creation_id" class="block text-orange-600 font-medium">Task created by:</label>
                        <input type="text" id="task_creation_id" name="task_created_by" class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500 ml-0 h-11" placeholder="Optional field">
                    </div>
                    <!-- Task assignation -->
                    <div class="w-60">
                        <label for="task_assignation_id" class="block text-orange-600 font-medium">Task assigned to:</label>
                        <input type="text" id="task_assignation_id" name="task_assigned_to" class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500 h-11" placeholder="Optional field">
                    </div>
                </div>
                <div class="w-1/4 mx-4"></div>
            </div>

            <!-- Submit Button -->
            <div class="flex justify-center">
                <button type="submit" class="bg-orange-600 text-white px-4 py-2 rounded-md hover:bg-lime-500">Search</button>
            </div>

        </form>
    <div/>
<div/>