
<!-- This script is responsible for generating the update form for a existing task -->

<div class="flex my-auto">
    <div class="w-3/5 mx-auto p-4">
        <h2 class="mb-4 text-2xl font-semibold text-center text-orange-400">UPDATE A TASK</h2>
        <form action="updateTask" method="post" class="text-orange-400" autocomplete="off">

            <!-- ID: -->
            <!-- Hidden input -->
            <input type="text" id="taskId_id" name="task_id" value="<?php echo $this->task_id;?>" required style="display:none">

            <!-- Task name and task status-->
            <div class="mb-4 px-2 flex">
                <!-- Task name -->
                <div class="w-2/3 pr-2">
                        <label for="task_name_id" class="block text-orange-600 font-medium">Task name:</label>
                        <input type="text" id="task_name_id" name="task_name" value="<?php echo $this->task_name;?>" required class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500">
                </div>
                <!-- Task status -->
                <div class="w-1/3 pl-2">
                    <label for="task_status_id" class="block text-orange-600 font-medium">Status:</label>
                    <select id="task_status_id" name="task_status" required class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500">
                        <option value="Pending" <?php echo ($this->task_status=="Pending") ? 'selected' : ''; ?>>Pending</option>
                        <option value="In Progress" <?php echo ($this->task_status=="In Progress") ? 'selected' : ''; ?>>In Progress</option>
                        <option value="Completed" <?php echo ($this->task_status=="Completed") ? 'selected' : ''; ?>>Completed</option>
                    </select>
                </div>
            </div>

            <!-- Task details -->
            <div class="mb-4 px-2">
                <label for="task_details_id" class="block text-orange-600 font-medium">Task details:</label>
                <textarea id="task_details_id" name="task_details" rows="1" required class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500"><?php echo $this->task_details;?></textarea>
            </div>

            <div class="flex mb-4">

                <!-- Created By -->
                <div class="w-1/3 px-2">
                    <label for="task_creation_id" class="block text-orange-600 font-medium">Created by:</label>
                    <input type="text" id="task_creation_id" name="task_created_by" value="<?php echo $this->task_created_by;?>" required class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500 ml-0">
                </div>

                <!-- Task assignation -->
                <div class="w-1/3 px-2">
                    <label for="task_assignation_id" class="block text-orange-600 font-medium">Task assigned to:</label>
                    <input type="text" id="task_assignation_id" name="task_assigned_to" value="<?php echo $this->task_assigned_to;?>" required class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500">
                </div>

                <!-- Start date -->
                <div class="w-1/3 px-2">
                    <label for="task_startDate_id" class="block text-orange-600 font-medium">Start date:</label>
                    <input type="date" id="task_startDate_id" name="task_startDate" value="<?php echo $this->task_creation_date;?>" required min="<?php echo $this->task_creation_date;?>" class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500">
                </div>

                <!-- Deadline -->
                <div class="w-1/3 px-2">
                    <label for="task_deadline_id" class="block text-orange-600 font-medium">Deadline:</label>
                    <input type="date" id="task_deadline_id" name="task_deadline" value="<?php echo $this->task_deadline;?>" required min="<?php echo $this->task_creation_date;?>" class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-orange-500">
                </div>

            </div>

            <!-- Submit Button -->
            <div class="flex justify-center">
                <button type="submit" class="bg-orange-600 text-white px-4 py-2 mt-4 rounded-md hover:bg-lime-500">Update task</button>
            </div>

        </form>
    <div/>
<div/>