<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>TO DO LIST</title>
	<link rel="stylesheet" href="http://<?php echo $_SERVER['HTTP_HOST']."/".WEB_ROOT?>/stylesheets/styles.css">
	<script src="https://cdn.tailwindcss.com"></script>
	<script src="javascripts/functions.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />

</head>

<body class="min-h-screen flex flex-col ">

	<header class="bg-orange-500 p-1 flex items-center justify-center w-full fixed top-0 z-50">
		<!-- Title -->
		<div class="flex-shrink-0 mr-10 hover:scale-110 transition-all duration-3000">
			<a href="<?php echo WEB_ROOT?>">
				<img src="http://<?php echo $_SERVER['HTTP_HOST']."/".WEB_ROOT?>/images/todolisticon.png" alt="todolist_icon" class="w-15 h-13">
			</a>
		</div>
		<!-- Navigation -->
		<div class="w-3/7 p-2 ml-10 flex justify-end items-center text-sm">
			<!-- Create task -->
			<div class="mb-2 mr-10 hover:scale-150 transition-all duration-2000"><a href="<?php echo WEB_ROOT . "/getinsertform"?>"><img title="Create new task" src="http://<?php echo $_SERVER['HTTP_HOST']."/".WEB_ROOT?>/images/newTask.png" class="w-12 h-12"></a></div>
			<!-- Search TASK -->
			<div class="mb-2 hover:scale-150 transition-all duration-2000"><a href="<?php echo WEB_ROOT . "/getsearchform"?>"><img title="Search a task" src="http://<?php echo $_SERVER['HTTP_HOST']."/".WEB_ROOT?>/images/searchTask.png" class="w-12 h-12"></a></div>
		</div>
	</header>

	<main class="flex-grow flex flex-col h-full mt-24 mb-10">
    	<?= $this->content() ?>		
  	</main>

    <footer class="flex justify-center bg-gray-800 text-white p-4 text-center mt-auto">
		<div class="flex justify-center w-1/3">
			<p class="text-white mt-2">App created by</p>
			<div class="flex items-center justify-center mt-2">
				<a href="https://www.linkedin.com/in/agonzalezar" class="flex items-center text-white text-lg mx-5">
					<img src="http://<?php echo $_SERVER['HTTP_HOST']."/".WEB_ROOT?>/images/linkedin.png" alt="Enlace 2 Icon" class="w-6 h-6 mr-2">
					Antonio González
				</a>
			</div>
		</div>
    </footer>


</body>
</html>